### ISSUE TITLE
Enhance opcache gui

### ISSUE THREAD

**Issue by mircobabini** [nierdz/flush-opcache#16]
Nice to meet you.

What do you think about switching from opcache-status to [PeeHaa/OpCacheGUI](https://github.com/PeeHaa/OpCacheGUI).
It's more complete and permits to invalidate any single cached file.

**Comment by nierdz** [comment]
That's a good idea, I will look into this in the next few days. The only caveats is this project seems to be dead (no commit since Feb 28, 2018).
Last year, I searched for a better opcache-status alternative and didn't find anything suitable or maintained anymore.

Do you know other projects like this one and still maintained ?

**Comment by mircobabini** [comment]
Yeah, this one: https://github.com/amnuts/opcache-gui

**Comment by nierdz** [comment]
Just so you know I'm working on used a modified version of this library. It's still WIP but I slowly progress. I hope to deliver it soon. The PR is [here](https://github.com/nierdz/flush-opcache/pull/17)

**Comment by nierdz** [comment]
I just released a new version addressing your issue. Let me know what you think about it.

**Comment by nierdz** [comment]
I consider this issue resolved.
